### ISSUE TITLE
Add option for specifying remote gateway

### ISSUE THREAD

**Issue by jsolly** [easierdata/ipfs-stac#1]
## Context 
Currently, we can specify a local_gateway to point to an IPFS instance on the local machine.

It would be nice if there was another parameter that allowed you to specify a remote gateway to use. For example, I read through the source code and see these options:
```
"http://127.0.0.1:8080,https://ipfs.io,https://gateway.pinata.cloud,https://cloudflare-ipfs.com",https://dweb.link"
```
### Possible Solution
Add a second parameter to the client creation command
```
easier = client.web3(remote_gateway="https://ipfs.io" stac="")
```

**Comment by jsolly** [comment]
Hey @matthewnanas. We should include a commit or a PR where a feature was implemented. No worries if other fixes were included.

Would also be good to know how the remote gateway can be used.

**Comment by jsolly** [comment]
It looks like the PR is still open?
https://github.com/easierdata/ipfs-stac/pull/15

**Comment by matthewnanas** [comment]
Addressed comments and merged
