### ISSUE TITLE
Add ability to print a list of all pinned CIDs

### ISSUE THREAD

**Issue by jsolly** [easierdata/ipfs-stac#10]
## Context 
In the blog post I am writing, I am currently doing this to show the CIDs we have pinned during the tutorial
```py
pinned_files = subprocess.run(["ipfs", "pin", "ls", "--type=recursive"], capture_output=True)

print(pinned_files.stdout.decode())
> QmbkCHHZJ3UoywA7DhnqFfBD6CVPUpFu7QajMg9Tp66JwL recursive
> QmQPeNsJPyVWPFDVHb77w8G42Fvo15z4bG2X8D2GhfbSXc recursive
> QmTgttqUf7PvZgdSoe71j3njeEKk1hC3h22n2sQmety3To recursive
> QmZkWaKSuVhFKtAwNbxSogcT6hXHMksXjhgqLu6AXHSUKq recursive
> Qmb1CYiG5Bc9FHDv47ZYPzQ6GuPDydXfxKVRBjKcMayosN recursive
```
We need a way a way to do this without using `subprocess`

## Things to consider
This seems like a feature for `ipfsspec`. If it's easy for us to add the feature there, great. If not, we can do it here.

Maybe we could do  `client.list_pinned()`

**Comment by matthewnanas** [comment]
Addressed and merged into new version
