### ISSUE TITLE
Asset gateway and port can become stale when a new gateway is chosen

### ISSUE THREAD

**Issue by jsolly** [easierdata/ipfs-stac#14]
## Context
When certain functions are run such as `getAssetFromItem` an Asset object is created and hydrated with the gateway and port currently in the `Web3` client object.

If this Web3 object is re-initialized, the assets that were created from this client will not receive any updates to the gateway or port.

## Ideal workflow
Not sure what the solution should be here.

Should we allow multiple `Web3` clients in one session?

Should updates to one instance of `Web3` propagate to assets created with this client?

## Further Thoughts
I ran into this issue because I had been working with some Assets in a notebook when I realized I needed to change the gateway in my client. I realized I needed to 're-up' my Assets so that they could get the right gateways and ports.

**Comment by matthewnanas** [comment]
Add a reference to this in the documentation, decided not to implement (for now)
