### ISSUE TITLE
Add ability to start IPFS Daemon from Python

### ISSUE THREAD

**Issue by jsolly** [easierdata/ipfs-stac#3]
## Context 
This might be a long-shot, but it would be cool if the Python Client had the ability to start the local Daemon by itself. Does that even make sense?

**Comment by jsolly** [comment]
I implemented this kind of functionality in https://github.com/easierdata/ipfs-stac/blob/main/tests/base.py

Can this functionality be added to the `init` class so it follows this workflow:
```py
if not local_gateway:
    # use an external gateway
else:
  try:
      # access local gateway
  except LocalGateWayNotFound:
      try:
          # try to start local node and re-try a few times.
     except LocalNodeNotAbleToStart:
          # use an external gateway
````

**Comment by matthewnanas** [comment]
Opened a [PR](https://github.com/easierdata/ipfs-stac/pull/11) for this card
