### ISSUE TITLE
Update how the `fetch` method saves to self.data

### ISSUE THREAD

**Issue by SethDocherty** [easierdata/ipfs-stac#41]
We are fetching content from IPFS calling `ipfs://{self.cid}`, which impacts performance in some use cases. For example, if we already have content pinned to our local node and fetch the content, it is announced over the IPFS network and retrieved from peers even though it may already be pinned on the local ipfs node.

I'm not sure why it behaves like that but using the Kubo RPC API yields MUCH better results, such as [cat](https://docs.ipfs.tech/reference/kubo/rpc/#api-v0-cat).

---
### UPDATE:
Considering my comments below, I don't see a need to replace `ipfs://{self.cid}` with a command from the Kubo RPC API.

Let's update the `fetch` method to save `self.data` as a bytes object instead of `BytesIO`. Note that there's likely an overlap with #40.

**Comment by SethDocherty** [comment]
Is there a reason why `self.data` is saved as a BytesIO object [here](https://github.com/easierdata/ipfs-stac/blob/bacfa3c32e81bfec354945ee86e332d42c4f2983/ipfs_stac/client.py#L265).

It may likely have to do `yaspin`. I'm running into an issue where I must read in self.data as raw bytes. I've only had success in reading the content with the cat api call I mentioned in the original post.

```python
    import h5py
    from io import BytesIO

def print_granule_metadata(client_obj,):

    with h5py.File(BytesIO(client_obj), "r") as hf:
        # read the METADATA group
        for name in hf:
            print(name)
        print("\nDetailed structure (first level):")


resp = requests.post(
    f"http://{easier_client.local_gateway}:{easier_client.api_port}/api/v0/cat?arg=/ipfs/{fetched_asset.cid}&progress=true"
)
print_granule_metadata(resp._content)
```

**Comment by SethDocherty** [comment]
After additional investigation, I identified that the method [getFromCID](https://github.com/easierdata/ipfs-stac/blob/9802e93ed83019c99d9817b47c655f1260832cd3/ipfs_stac/client.py#L135) is also reading the data the same way, `ipfs://{self.cid}` but the return type is `bytes` where as the `fetch` method stores `self.data` as a BytesIO object.

**Comment by matthewnanas** [comment]
One more quick run through maybe and pull if all works well!
