### ISSUE TITLE
Enhancing Web3 Class

### ISSUE THREAD

**Issue by SethDocherty** [easierdata/ipfs-stac#44]
> This issue is a WIP to capture enhancement ideas

When instantiating a Web3 object, I believe we should be doing a few more things:

1. Creating a [client instance](https://pystac-client.readthedocs.io/en/stable/usage.html#client) which is a property of `Web3`.
    - This will significantly enhance the interaction with the STAC API, which could be extended to other methods within `Web3`. 
        - See Issues #37 #38 #39 
    - I'm unsure if inheriting the class properties would be the best approach.
    - Since we have to pass in a `stac_endpoint` URL, it makes sense that the web3 object that's created is tied to that specific endpoint.
2. Creating an IPFS configuration property.
    - This would represent the content of the [configuration file](https://github.com/ipfs/kubo/blob/master/docs/config.md#the-kubo-config-file) but stored in memory.   We can use the kubo API to generate our [configuration settings](http://bafybeibdpv3fpnarxhxouk3e5eskkkxfygohvg367jliondx7bq2a646qy.ipfs.localhost:8081/reference/kubo/cli/#ipfs-config) that can be modified with the python class

**Comment by matthewnanas** [comment]
(Commenting to keep organized), second point had been pushed with https://github.com/easierdata/ipfs-stac/commit/22a1e550ea401ee91aa25915e2296664053f2829 overwriting the current config was pushed in bd798ccf4de9cda099218c5ab5de65299cb49ad7

**Comment by matthewnanas** [comment]
It seems 37 has already been addressed but I have added a function that returns only catalogs as objects instead of IDs (we can scrap this if it's redundant). 38 Is now addressed with 7aa51f55f0ee8648933379c4c0bcb953cc4d4d55

Reference the following sample
`
from ipfs_stac.client import Web3

client = Web3(stac_endpoint="http://stac.easierdata.info/")

collections = client.get_collections()
tmp = collections[0]

assets = client.getAssetNames(tmp)
print(assets)
`

**Comment by SethDocherty** [comment]
> (Commenting to keep organized), second point had been pushed with [22a1e55](https://github.com/easierdata/ipfs-stac/commit/22a1e550ea401ee91aa25915e2296664053f2829) overwriting the current config was pushed in [bd798cc](https://github.com/easierdata/ipfs-stac/commit/bd798ccf4de9cda099218c5ab5de65299cb49ad7)

This is a much cleaner approach.  The approach here is that a user must run this method manually if they would like to update the default configuration?

Remind me again: Are the settings found in `.ipfs/config` used if the IPFS daemon is not already running?

**Comment by SethDocherty** [comment]
Closing this issue since the majority of the asks here have been resolved and merged into main.  A new issue was created specifically for the ipfs configuration file.
