### ISSUE TITLE
Refactor ForceLocalNode so that it uses environment variables instead of a .env file

### ISSUE THREAD

**Issue by jsolly** [easierdata/ipfs-stac#9]
## Context 
Currently, this function writes to a .env file the values of IPFSSPEC_GATEWAYS

## Current Behavior/Workaround
I am venturing to guess `ipfsspec` is just accessing this variable using `os.environ.get()` so we can just put it into the user's environment variables without having to write to a file.

## Ideal behavior
We don't need to write to any local files.

**Comment by matthewnanas** [comment]
Refactored and merged into main
